<a href="https://colab.research.google.com/github/AbdulHaqq2001/Database_management/blob/main/Mid_Term_Abdulkhak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3

# Connect to the SQLite database (or create it if it doesn't exist)
conn = sqlite3.connect('ITS_database.db')

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Create the Vehicle table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Vehicle (
        VehicleId INTEGER PRIMARY KEY,
        RegistrationId TEXT,
        Manufacturer TEXT,
        Model TEXT,
        Color TEXT,
        CurrentOdometer INTEGER,
        PassengerCapacity INTEGER
    )
''')

# Create the Maintenance and Repair History table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS MaintenanceRepairHistory (
        RecordId INTEGER PRIMARY KEY,
        VehicleId INTEGER,
        ActionType TEXT,
        Odometer INTEGER,
        FinalCost REAL,
        Description TEXT,
        Date DATE,
        FOREIGN KEY (VehicleId) REFERENCES Vehicle (VehicleId)
    )
''')

# Create the Country and Spoken Languages table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS CountrySpokenLanguages (
        CountryCode TEXT PRIMARY KEY,
        CountryName TEXT,
        SpokenLanguage TEXT
    )
''')

# Create the Game Officials table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS GameOfficials (
        OfficialId INTEGER PRIMARY KEY,
        CountryCode TEXT,
        IncheonCityId TEXT,
        Name TEXT,
        Role TEXT,
        PreferredLanguage TEXT,
        FOREIGN KEY (CountryCode) REFERENCES CountrySpokenLanguages (CountryCode)
    )
''')

# Create the Driver table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Driver (
        DriverId INTEGER PRIMARY KEY,
        Name TEXT,
        LicenseNumber TEXT,
        ClearanceLevel INTEGER,
        FirstAidTrainingLevel INTEGER,
        FirstAidTrainingDate DATE,
        STLVTLevel INTEGER,
        STLVTQualificationDate DATE,
        CertifyingAuthority TEXT
    )
''')

# Create the Driver Availability table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS DriverAvailability (
        DriverId INTEGER,
        VehicleId INTEGER,
        Available BOOLEAN,
        PickupLocationName TEXT,
        PickupLocationAddress TEXT,
        PickupLocationType TEXT,
        DropOffLocationName TEXT,
        DropOffLocationAddress TEXT,
        DropOffLocationType TEXT,
        FOREIGN KEY (DriverId) REFERENCES Driver (DriverId),
        FOREIGN KEY (VehicleId) REFERENCES Vehicle (VehicleId)
    )
''')

# Create the Trip History table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS TripHistory (
        BookingReferenceNumber TEXT PRIMARY KEY,
        DriverId INTEGER,
        VehicleId INTEGER,
        OfficialId INTEGER,
        StartDateTime DATETIME,
        EndDateTime DATETIME,
        StartOdometer INTEGER,
        EndOdometer INTEGER,
        TripStatus TEXT
    )
''')

# Commit changes and close the database connection
conn.commit()
conn.close()

In [2]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('ITS_database.db')
cursor = conn.cursor()

# Insert records into the Vehicle table
vehicle_data = [
    (1000, '2001 ABC', 'Volvo', 'XC90 SE', 'Silver', 4350, 4),
    (1001, '2006 AFD', 'Kia', 'K7', 'Black', 2195, 4),
    (1002, '2021 AHR', 'Tesla', '2020 F', 'White', 509, 4),
    (1003, '2020 DXF', 'Ford', 'Transit', 'Silver', 974, 2)
]

cursor.executemany('''
    INSERT INTO Vehicle (VehicleId, RegistrationId, Manufacturer, Model, Color, CurrentOdometer, PassengerCapacity)
    VALUES (?, ?, ?, ?, ?, ?, ?)
''', vehicle_data)

# Insert records into the Country and Spoken Languages table
country_language_data = [
    ('KR', 'Republic of Korea', 'EN'),
    ('US', 'United States', 'EN'),
    ('JP', 'Japan', 'JA')
]

cursor.executemany('''
    INSERT INTO CountrySpokenLanguages (CountryCode, CountryName, SpokenLanguage)
    VALUES (?, ?, ?)
''', country_language_data)

# Insert records into the Game Officials table
officials_data = [
    (1, 'KR', 'INCH1234', 'John Doe', 'Coach', 'EN'),
    (2, 'US', 'INCH5678', 'Jane Smith', 'Judge', 'EN'),
    (3, 'JP', 'INCH9012', 'Taro Yamada', 'Physician', 'JA')
]

cursor.executemany('''
    INSERT INTO GameOfficials (OfficialId, CountryCode, IncheonCityId, Name, Role, PreferredLanguage)
    VALUES (?, ?, ?, ?, ?, ?)
''', officials_data)

# Insert records into the Driver table
driver_data = [
    (1, 'Alice Johnson', 'DL12345678901234567', 4, 7, '2023-01-15', 3, 'Local Police'),
    (2, 'Bob Smith', 'DL98765432109876543', 3, 5, '2023-02-20', 2, 'Foreign Police'),
]

cursor.executemany('''
    INSERT INTO Driver (DriverId, Name, LicenseNumber, ClearanceLevel, FirstAidTrainingLevel, FirstAidTrainingDate, STLVTLevel, CertifyingAuthority)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
''', driver_data)

# Commit changes and close the database connection
conn.commit()
conn.close()